# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

project_name: url_shortner

version: 1

# gomod:
#   proxy: true

env:
  - GO111MODULE=on
  - CGO_ENABLED=1
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - COSIGN_YES=true
  - LATEST_TAG=,latest

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

sboms:
  - artifacts: archive

builds:
  - id: linux-amd64-{{ .Arch }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    binary: url_shortner-linux-{{ .Arch }}
    main: ./cmd/url_shortner
    mod_timestamp: '{{ .CommitTimestamp }}'
    

  - id: windows-amd64
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -buildmode=exe
      - -s -w
        -X "github.com/viveksahu26/url_shortner/buildversion.BuildVersion={{.Version}}"
        -X "github.com/viveksahu26/url_shortner/buildversion.BuildTime={{time "2006-01-02T15:04:05Z07:00"}}"
        -X "github.com/viveksahu26/url_shortner/buildversion.BuildCommit={{.FullCommit}}"
    binary: url_shortner-windows-{{ .Arch }}
    main: ./cmd/url_shortner


archives:
  - format: binary
    name_template: "{{ .Binary }}"
    allow_different_binary_count: true
    
  # - format: tar.gz
  #   name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  #   allow_different_binary_count: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  - id: url_shortner
    package_name: url_shortner
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: viveksahu26
    homepage: https://github.com/viveksahu26/
    maintainer: viveksahu26
    builds:
      - linux
    description: It primarily used for converting long URL into short
    license: "Apache License 2.0"
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: /usr/bin/url_shortner-linux-{{ .Arch }}
        dst: /usr/bin/url_shortner
        type: "symlink"
